### ISSUE TITLE
No endpoint-specific DATASET_PREFIX

### ISSUE THREAD

**Issue by jotelha** [jic-dtool/dtool-s3#11]
Hello!

I noticed a subtle difference to `dtool-ecs`: the `DATASET_PREFIX` parameter used to be endpoint-specific within `dtool-ecs`, see https://github.com/jic-dtool/dtool-ecs/blob/c5a7fabfdd0f94ee9ad0473879a6b1a7f2d36be8/dtool_ecs/storagebroker.py#L86, but is not anymore after implementation here, 
https://github.com/jic-dtool/dtool-s3/blob/b0b98c9200865ba263d3a1db55b78cc844717935/dtool_s3/storagebroker.py#L208

Is that diverging behavior intended?

I would suggest to make it an endpoint-specific parameter again if nothing speaks against it, just like the other s3 parameters in 
https://github.com/jic-dtool/dtool-s3/blob/b0b98c9200865ba263d3a1db55b78cc844717935/dtool_s3/storagebroker.py#L246-L254
Will prepare an according little pull request.

**Comment by tjelvar-olsson** [comment]
Included in https://pypi.org/project/dtool-s3/0.14.0/

@jotelha thank you for this :)
