### ISSUE TITLE
Add test for user-specified prefix for object path functionality

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-s3#4]
Add test to check behaviour of: https://github.com/jic-dtool/dtool-s3/pull/3

It should be relatively easy to do using the tmp_env_var decorator: https://github.com/jic-dtool/dtool-s3/blob/master/tests/__init__.py#L22

and DTOOL_S3_DATASET_PREFIX environment variable

@pastewka

**Comment by tjelvar-olsson** [comment]
Added skeleton code for test in https://github.com/jic-dtool/dtool-s3/commit/8c2768603b8313df81a6e290bf49ca8d703aab2c

**Comment by pastewka** [comment]
Yes that sounds good. The ECS has a similar environment variable.

**Comment by tjelvar-olsson** [comment]
Implemented in 21f2e8f
